# Generated by Django 2.1.4 on 2019-01-17 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('unique', 'Unica')], max_length=20)),
                ('state', models.CharField(choices=[('1', 'Pendiente'), ('2', 'En proceso'), ('3', 'Terminado')], default='1', max_length=20)),
                ('expired', models.BooleanField(default=False)),
                ('responsible', models.ForeignKey(on_delete='PROTECTED', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
