# Generated by Django 2.1.4 on 2019-01-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='activity',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
    ]
