# Generated by Django 2.1.4 on 2019-01-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190112_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'En proceso'), ('3', 'Terminado')], default=None, max_length=20),
        ),
    ]
