# Generated by Django 2.1.4 on 2019-01-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_activity_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'En proceso'), ('3', 'Terminado')], max_length=20),
        ),
    ]
