# Generated by Django 2.1.4 on 2019-01-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190113_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Terminado')], default=1, max_length=20),
        ),
    ]
