# Generated by Django 2.1.4 on 2019-01-17 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20190117_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
    ]
