# Generated by Django 2.1.4 on 2019-01-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20190117_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(choices=[('1', 'Pendiente'), ('3', 'Terminado')], default='1', max_length=20),
        ),
    ]
