# Generated by Django 2.1.4 on 2019-01-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20190118_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedUnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedWeekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PendingDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PendingMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PendingUnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PendingWeekly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Terminado')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingweekly',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
        migrations.AddField(
            model_name='pendingunique',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
        migrations.AddField(
            model_name='pendingmonthly',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
        migrations.AddField(
            model_name='pendingdaily',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
        migrations.AddField(
            model_name='finishedweekly',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
        migrations.AddField(
            model_name='finishedunique',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
        migrations.AddField(
            model_name='finishedmonthly',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
        migrations.AddField(
            model_name='finisheddaily',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Activity'),
        ),
    ]
