# Generated by Django 2.1.4 on 2019-01-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20190118_0224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinishedDaily',
            new_name='Finish',
        ),
        migrations.RenameModel(
            old_name='FinishedWeekly',
            new_name='Pending',
        ),
        migrations.RemoveField(
            model_name='finishedmonthly',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='finishedunique',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='pendingdaily',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='pendingmonthly',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='pendingunique',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='pendingweekly',
            name='activity',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='finish',
            options={'verbose_name': 'Actividad terminada', 'verbose_name_plural': 'Actividades terminadas'},
        ),
        migrations.AlterModelOptions(
            name='pending',
            options={'verbose_name': 'Actividad pendiente', 'verbose_name_plural': 'Actividades pendientes'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='start_date',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='finish_date',
            new_name='fecha_terminacion',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='frequency',
            new_name='frecuencia',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='responsible',
            new_name='responsable',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='activity',
            new_name='actividad',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date',
            new_name='fecha_reporte',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='state',
        ),
        migrations.AddField(
            model_name='activity',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente'), ('2', 'Terminado'), ('3', 'Expirado')], default='1', max_length=20),
        ),
        migrations.DeleteModel(
            name='FinishedMonthly',
        ),
        migrations.DeleteModel(
            name='FinishedUnique',
        ),
        migrations.DeleteModel(
            name='PendingDaily',
        ),
        migrations.DeleteModel(
            name='PendingMonthly',
        ),
        migrations.DeleteModel(
            name='PendingUnique',
        ),
        migrations.DeleteModel(
            name='PendingWeekly',
        ),
    ]
