# Generated by Django 2.1.4 on 2019-01-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20190119_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finish',
            old_name='activity',
            new_name='actividad',
        ),
        migrations.RenameField(
            model_name='pending',
            old_name='activity',
            new_name='actividad',
        ),
        migrations.AlterField(
            model_name='activity',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Terminado', 'Terminado'), ('Expirado', 'Expirado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='frecuencia',
            field=models.CharField(choices=[('Diaria', 'Diaria'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Unica', 'Unica')], max_length=20),
        ),
    ]
